apiVersion: v1
kind: Service
metadata:
  name:  congthanh-rtp-service
  namespace: congthanh
spec:
  type: NodePort
  selector:
    app: congthanh-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000